project:
  type: website
  output-dir: docs

website:
  title: "KNN Tutorial"
  navbar:
    left:
      - index.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com

format:
  html:
    theme: cosmo
    css: styles.css
    
execute:
  echo: true
  warning: false
  error: false
  
jupyter: python3